name: 02 - PR CI

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-ci:
    name: PR Checks (Gradle JUnit)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-and-test/action

      - name: Summary
        if: always()
        run: |
          echo "### PR CI summary" >> "$GITHUB_STEP_SUMMARY"
          echo "- JDK: 21" >> "$GITHUB_STEP_SUMMARY"
          echo "- Branch: ${{ github.head_ref || github.ref_name }}" >> "$GITHUB_STEP_SUMMARY"
