name: 03 - Matrix Builds

on:
  #pull_request:
  workflow_dispatch:

jobs:
  test-matrix:
    name: JDK${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17, 21]

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: Test
        run: |
          # Use wrapper for cross-platform (gradlew vs gradlew.bat is handled)
          ./gradlew clean test --no-daemon
