name: 04 - Cache & Artifacts

on:
  #pull_request:
  workflow_dispatch:

jobs:
  test-with-cache:
    name: Tests with Gradle cache + reports
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Built-in Gradle cache handled by setup-java
      - name: Setup Java (Temurin 21) + Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Run tests
        run: ./gradlew clean test --no-daemon

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        if: always()  # keep reports even on failures
        with:
          name: test-reports
          path: |
            build/reports/tests/test/**
            **/build/reports/tests/test/**
          retention-days: 7

      - name: Summary
        if: always()
        run: |
          echo "### Cache & Artifacts" >> "$GITHUB_STEP_SUMMARY"
          echo "- Gradle cache: enabled via setup-java" >> "$GITHUB_STEP_SUMMARY"
          echo "- Reports uploaded: test-reports" >> "$GITHUB_STEP_SUMMARY"
