name: 05 - Secrets & Environments

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Target environment"
        type: choice
        required: true
        options: [staging, prod]
        default: prod

jobs:
  deploy:
    # This binds the job to an Environment with the same name.
    # Configure env secrets + required reviewers in repo Settings.
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write  # needed to create/update environment deployments

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (Temurin 21)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Build (release artifact)
        run: ./gradlew clean build --no-daemon

      # Demonstrate using an environment-scoped secret safely.
      - name: Use secret without leaking
        run: |
          echo "Deploying to: ${{ inputs.env }}"
          # Never print the actual secret; this only shows length, which is masked-safe.
          echo "PROD_API_KEY length: ${#PROD_API_KEY}"
        env:
          PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
        shell: bash

      - name: Mark environment deployment
        run: |
          echo "### Deployment Summary" >> "$GITHUB_STEP_SUMMARY"
          echo "- Environment: ${{ inputs.env }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Artifact: $(ls -1 build/libs | head -n 1 || echo 'none')" >> "$GITHUB_STEP_SUMMARY"
